name: Latest blog post workflow
on:
  # Temporarily disabled - 暂时停掉
  # schedule:
  #   # Runs every hour
  #   - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master       
        with:
          disable_cache: true
          feed_list: "https://zhu-jl18.github.io/atom.xml"
          max_post_count: 5
          # ⬇️ 这是我们最终的、最简单、最可靠的模板 ⬇️
          template: '<p align="center"><a href="$url" style="text-decoration: none; color: #20B2AA;">$title</a></p>'
